#import "project.h"

/// Generated from project.pbxproj
__attribute__((visibility("hidden")))
NSDictionary * const project = @{
    @"archiveVersion" : @"1",
    @"classes" : @{
    },
    @"objects" : @{
        @"1AE116F6C05CAC852900401C" : @{
            @"buildActionMask" : @2147483647,
            @"files" : @[
                @"AF982C065F28985B78EC108A",
                @"413131E9E0B122613137EFB8",
                @"A697FA7F34CF00352EEC4B8B",
            ],
            @"isa" : @"PBXSourcesBuildPhase",
            @"runOnlyForDeploymentPostprocessing" : @0,
        },
        @"1B5F23F33664958D5B778682" : @{
            @"fileRef" : @"8A2CA69581E78374CE81A0A7",
            @"isa" : @"PBXBuildFile",
        },
        @"4FCD6F3A563B65A71839C33E" : @{
            @"isa" : @"PBXFileReference",
            @"lastKnownFileType" : @"sourcecode.swift",
            @"name" : @"SunShading.swift",
            @"path" : @"WorldClockWidget/SunShading.swift",
            @"sourceTree" : @"SOURCE_ROOT",
        },
        @"7AFA3C8E1D35360C0083082E" : @{
            @"isa" : @"PBXFileReference",
            @"lastKnownFileType" : @"text.xcconfig",
            @"path" : @"Release.xcconfig",
            @"sourceTree" : @"<group>",
        },
        @"8A2CA69581E78374CE81A0A7" : @{
            @"explicitFileType" : @"wrapper.app-extension",
            @"includeInIndex" : @0,
            @"isa" : @"PBXFileReference",
            @"path" : @"WorldClockWidget.appex",
            @"sourceTree" : @"BUILT_PRODUCTS_DIR",
        },
        @"33BA886A226E78AF003329D5" : @{
            @"children" : @[
                @"33E5194F232828860026EE4D",
                @"9740EEB21CF90195004384FC",
                @"7AFA3C8E1D35360C0083082E",
                @"333000ED22D3DE5D00554162",
            ],
            @"isa" : @"PBXGroup",
            @"path" : @"Configs",
            @"sourceTree" : @"<group>",
        },
        @"33CC10E42044A3C60003C045" : @{
            @"children" : @[
                @"33FAB671232836740065AC1E",
                @"33CEB47122A05771004F2AC0",
                @"331C80D6294CF71000263BE5",
                @"33CC10EE2044A3C60003C045",
                @"D73912EC22F37F3D000D13A0",
                @"924A62FDA3B40BC9FE5B372E",
            ],
            @"isa" : @"PBXGroup",
            @"sourceTree" : @"<group>",
        },
        @"33CC10E52044A3C60003C045" : @{
            @"attributes" : @{
                @"BuildIndependentTargetsInParallel" : @"YES",
                @"LastSwiftUpdateCheck" : @"0920",
                @"LastUpgradeCheck" : @"1510",
                @"ORGANIZATIONNAME" : @"",
                @"TargetAttributes" : @{
                    @"33CC10EC2044A3C60003C045" : @{
                        @"CreatedOnToolsVersion" : @"9.2",
                        @"LastSwiftMigration" : @"1100",
                        @"ProvisioningStyle" : @"Automatic",
                        @"SystemCapabilities" : @{
                            @"com.apple.Sandbox" : @{
                                @"enabled" : @"1",
                            },
                        },
                    },
                    @"33CC111A2044C6BA0003C045" : @{
                        @"CreatedOnToolsVersion" : @"9.2",
                        @"ProvisioningStyle" : @"Manual",
                    },
                    @"331C80D4294CF70F00263BE5" : @{
                        @"CreatedOnToolsVersion" : @"14.0",
                        @"TestTargetID" : @"33CC10EC2044A3C60003C045",
                    },
                },
            },
            @"buildConfigurationList" : @"33CC10E82044A3C60003C045",
            @"compatibilityVersion" : @"Xcode 9.3",
            @"developmentRegion" : @"en",
            @"hasScannedForEncodings" : @"0",
            @"isa" : @"PBXProject",
            @"knownRegions" : @[
                @"en",
                @"Base",
            ],
            @"mainGroup" : @"33CC10E42044A3C60003C045",
            @"packageReferences" : @[
                @"781AD8BC2B33823900A9FFBB",
            ],
            @"productRefGroup" : @"33CC10EE2044A3C60003C045",
            @"projectDirPath" : @"",
            @"projectRoot" : @"",
            @"targets" : @[
                @"33CC10EC2044A3C60003C045",
                @"331C80D4294CF70F00263BE5",
                @"33CC111A2044C6BA0003C045",
                @"A28F36DB2E18C8C4A691B925",
            ],
        },
        @"33CC10E82044A3C60003C045" : @{
            @"buildConfigurations" : @[
                @"33CC10F92044A3C60003C045",
                @"33CC10FA2044A3C60003C045",
                @"338D0CE9231458BD00FA5F75",
            ],
            @"defaultConfigurationIsVisible" : @"0",
            @"defaultConfigurationName" : @"Release",
            @"isa" : @"XCConfigurationList",
        },
        @"33CC10E92044A3C60003C045" : @{
            @"buildActionMask" : @"2147483647",
            @"files" : @[
                @"33CC11132044BFA00003C045",
                @"33CC10F12044A3C60003C045",
                @"335BBD1B22A9A15E00E9071D",
            ],
            @"isa" : @"PBXSourcesBuildPhase",
            @"runOnlyForDeploymentPostprocessing" : @"0",
        },
        @"33CC10EA2044A3C60003C045" : @{
            @"buildActionMask" : @"2147483647",
            @"files" : @[
                @"78A318202AECB46A00862997",
            ],
            @"isa" : @"PBXFrameworksBuildPhase",
            @"runOnlyForDeploymentPostprocessing" : @"0",
        },
        @"33CC10EB2044A3C60003C045" : @{
            @"buildActionMask" : @"2147483647",
            @"files" : @[
                @"33CC10F32044A3C60003C045",
                @"33CC10F62044A3C60003C045",
            ],
            @"isa" : @"PBXResourcesBuildPhase",
            @"runOnlyForDeploymentPostprocessing" : @"0",
        },
        @"33CC10EC2044A3C60003C045" : @{
            @"buildConfigurationList" : @"33CC10FB2044A3C60003C045",
            @"buildPhases" : @[
                @"33CC10E92044A3C60003C045",
                @"33CC10EA2044A3C60003C045",
                @"33CC10EB2044A3C60003C045",
                @"33CC110E2044A8840003C045",
                @"3399D490228B24CF009A79C7",
                @"372F46F5027C2809D7406829",
            ],
            @"buildRules" : @[
            ],
            @"dependencies" : @[
                @"33CC11202044C79F0003C045",
            ],
            @"isa" : @"PBXNativeTarget",
            @"name" : @"Runner",
            @"packageProductDependencies" : @[
                @"78A3181F2AECB46A00862997",
            ],
            @"productName" : @"Runner",
            @"productReference" : @"33CC10ED2044A3C60003C045",
            @"productType" : @"com.apple.product-type.application",
        },
        @"33CC10ED2044A3C60003C045" : @{
            @"explicitFileType" : @"wrapper.application",
            @"includeInIndex" : @"0",
            @"isa" : @"PBXFileReference",
            @"path" : @"world_clock.app",
            @"sourceTree" : @"BUILT_PRODUCTS_DIR",
        },
        @"33CC10EE2044A3C60003C045" : @{
            @"children" : @[
                @"33CC10ED2044A3C60003C045",
                @"331C80D5294CF71000263BE5",
                @"8A2CA69581E78374CE81A0A7",
            ],
            @"isa" : @"PBXGroup",
            @"name" : @"Products",
            @"sourceTree" : @"<group>",
        },
        @"33CC10F02044A3C60003C045" : @{
            @"isa" : @"PBXFileReference",
            @"lastKnownFileType" : @"sourcecode.swift",
            @"path" : @"AppDelegate.swift",
            @"sourceTree" : @"<group>",
        },
        @"33CC10F12044A3C60003C045" : @{
            @"fileRef" : @"33CC10F02044A3C60003C045",
            @"isa" : @"PBXBuildFile",
        },
        @"33CC10F22044A3C60003C045" : @{
            @"isa" : @"PBXFileReference",
            @"lastKnownFileType" : @"folder.assetcatalog",
            @"name" : @"Assets.xcassets",
            @"path" : @"Runner/Assets.xcassets",
            @"sourceTree" : @"<group>",
        },
        @"33CC10F32044A3C60003C045" : @{
            @"fileRef" : @"33CC10F22044A3C60003C045",
            @"isa" : @"PBXBuildFile",
        },
        @"33CC10F42044A3C60003C045" : @{
            @"children" : @[
                @"33CC10F52044A3C60003C045",
            ],
            @"isa" : @"PBXVariantGroup",
            @"name" : @"MainMenu.xib",
            @"path" : @"Runner",
            @"sourceTree" : @"<group>",
        },
        @"33CC10F52044A3C60003C045" : @{
            @"isa" : @"PBXFileReference",
            @"lastKnownFileType" : @"file.xib",
            @"name" : @"Base",
            @"path" : @"Base.lproj/MainMenu.xib",
            @"sourceTree" : @"<group>",
        },
        @"33CC10F62044A3C60003C045" : @{
            @"fileRef" : @"33CC10F42044A3C60003C045",
            @"isa" : @"PBXBuildFile",
        },
        @"33CC10F72044A3C60003C045" : @{
            @"isa" : @"PBXFileReference",
            @"lastKnownFileType" : @"text.plist.xml",
            @"name" : @"Info.plist",
            @"path" : @"Runner/Info.plist",
            @"sourceTree" : @"<group>",
        },
        @"33CC10F92044A3C60003C045" : @{
            @"baseConfigurationReference" : @"9740EEB21CF90195004384FC",
            @"buildSettings" : @{
                @"ALWAYS_SEARCH_USER_PATHS" : @"NO",
                @"ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS" : @"YES",
                @"CLANG_ANALYZER_NONNULL" : @"YES",
                @"CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION" : @"YES_AGGRESSIVE",
                @"CLANG_CXX_LANGUAGE_STANDARD" : @"gnu++14",
                @"CLANG_CXX_LIBRARY" : @"libc++",
                @"CLANG_ENABLE_MODULES" : @"YES",
                @"CLANG_ENABLE_OBJC_ARC" : @"YES",
                @"CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING" : @"YES",
                @"CLANG_WARN_BOOL_CONVERSION" : @"YES",
                @"CLANG_WARN_CONSTANT_CONVERSION" : @"YES",
                @"CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS" : @"YES",
                @"CLANG_WARN_DIRECT_OBJC_ISA_USAGE" : @"YES_ERROR",
                @"CLANG_WARN_DOCUMENTATION_COMMENTS" : @"YES",
                @"CLANG_WARN_EMPTY_BODY" : @"YES",
                @"CLANG_WARN_ENUM_CONVERSION" : @"YES",
                @"CLANG_WARN_INFINITE_RECURSION" : @"YES",
                @"CLANG_WARN_INT_CONVERSION" : @"YES",
                @"CLANG_WARN_NON_LITERAL_NULL_CONVERSION" : @"YES",
                @"CLANG_WARN_OBJC_LITERAL_CONVERSION" : @"YES",
                @"CLANG_WARN_OBJC_ROOT_CLASS" : @"YES_ERROR",
                @"CLANG_WARN_RANGE_LOOP_ANALYSIS" : @"YES",
                @"CLANG_WARN_SUSPICIOUS_MOVE" : @"YES",
                @"CODE_SIGN_IDENTITY" : @"-",
                @"COPY_PHASE_STRIP" : @"NO",
                @"DEAD_CODE_STRIPPING" : @"YES",
                @"DEBUG_INFORMATION_FORMAT" : @"dwarf",
                @"ENABLE_STRICT_OBJC_MSGSEND" : @"YES",
                @"ENABLE_TESTABILITY" : @"YES",
                @"ENABLE_USER_SCRIPT_SANDBOXING" : @"NO",
                @"GCC_C_LANGUAGE_STANDARD" : @"gnu11",
                @"GCC_DYNAMIC_NO_PIC" : @"NO",
                @"GCC_NO_COMMON_BLOCKS" : @"YES",
                @"GCC_OPTIMIZATION_LEVEL" : @"0",
                @"GCC_PREPROCESSOR_DEFINITIONS" : @[
                    @"DEBUG=1",
                    @"$(inherited)",
                ],
                @"GCC_WARN_64_TO_32_BIT_CONVERSION" : @"YES",
                @"GCC_WARN_ABOUT_RETURN_TYPE" : @"YES_ERROR",
                @"GCC_WARN_UNINITIALIZED_AUTOS" : @"YES_AGGRESSIVE",
                @"GCC_WARN_UNUSED_FUNCTION" : @"YES",
                @"GCC_WARN_UNUSED_VARIABLE" : @"YES",
                @"MACOSX_DEPLOYMENT_TARGET" : @"10.15",
                @"MTL_ENABLE_DEBUG_INFO" : @"YES",
                @"ONLY_ACTIVE_ARCH" : @"YES",
                @"SDKROOT" : @"macosx",
                @"SWIFT_ACTIVE_COMPILATION_CONDITIONS" : @"DEBUG",
                @"SWIFT_OPTIMIZATION_LEVEL" : @"-Onone",
            },
            @"isa" : @"XCBuildConfiguration",
            @"name" : @"Debug",
        },
        @"33CC10FA2044A3C60003C045" : @{
            @"baseConfigurationReference" : @"7AFA3C8E1D35360C0083082E",
            @"buildSettings" : @{
                @"ALWAYS_SEARCH_USER_PATHS" : @"NO",
                @"ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS" : @"YES",
                @"CLANG_ANALYZER_NONNULL" : @"YES",
                @"CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION" : @"YES_AGGRESSIVE",
                @"CLANG_CXX_LANGUAGE_STANDARD" : @"gnu++14",
                @"CLANG_CXX_LIBRARY" : @"libc++",
                @"CLANG_ENABLE_MODULES" : @"YES",
                @"CLANG_ENABLE_OBJC_ARC" : @"YES",
                @"CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING" : @"YES",
                @"CLANG_WARN_BOOL_CONVERSION" : @"YES",
                @"CLANG_WARN_CONSTANT_CONVERSION" : @"YES",
                @"CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS" : @"YES",
                @"CLANG_WARN_DIRECT_OBJC_ISA_USAGE" : @"YES_ERROR",
                @"CLANG_WARN_DOCUMENTATION_COMMENTS" : @"YES",
                @"CLANG_WARN_EMPTY_BODY" : @"YES",
                @"CLANG_WARN_ENUM_CONVERSION" : @"YES",
                @"CLANG_WARN_INFINITE_RECURSION" : @"YES",
                @"CLANG_WARN_INT_CONVERSION" : @"YES",
                @"CLANG_WARN_NON_LITERAL_NULL_CONVERSION" : @"YES",
                @"CLANG_WARN_OBJC_LITERAL_CONVERSION" : @"YES",
                @"CLANG_WARN_OBJC_ROOT_CLASS" : @"YES_ERROR",
                @"CLANG_WARN_RANGE_LOOP_ANALYSIS" : @"YES",
                @"CLANG_WARN_SUSPICIOUS_MOVE" : @"YES",
                @"CODE_SIGN_IDENTITY" : @"-",
                @"COPY_PHASE_STRIP" : @"NO",
                @"DEAD_CODE_STRIPPING" : @"YES",
                @"DEBUG_INFORMATION_FORMAT" : @"dwarf-with-dsym",
                @"ENABLE_NS_ASSERTIONS" : @"NO",
                @"ENABLE_STRICT_OBJC_MSGSEND" : @"YES",
                @"ENABLE_USER_SCRIPT_SANDBOXING" : @"NO",
                @"GCC_C_LANGUAGE_STANDARD" : @"gnu11",
                @"GCC_NO_COMMON_BLOCKS" : @"YES",
                @"GCC_WARN_64_TO_32_BIT_CONVERSION" : @"YES",
                @"GCC_WARN_ABOUT_RETURN_TYPE" : @"YES_ERROR",
                @"GCC_WARN_UNINITIALIZED_AUTOS" : @"YES_AGGRESSIVE",
                @"GCC_WARN_UNUSED_FUNCTION" : @"YES",
                @"GCC_WARN_UNUSED_VARIABLE" : @"YES",
                @"MACOSX_DEPLOYMENT_TARGET" : @"10.15",
                @"MTL_ENABLE_DEBUG_INFO" : @"NO",
                @"SDKROOT" : @"macosx",
                @"SWIFT_COMPILATION_MODE" : @"wholemodule",
                @"SWIFT_OPTIMIZATION_LEVEL" : @"-O",
            },
            @"isa" : @"XCBuildConfiguration",
            @"name" : @"Release",
        },
        @"33CC10FB2044A3C60003C045" : @{
            @"buildConfigurations" : @[
                @"33CC10FC2044A3C60003C045",
                @"33CC10FD2044A3C60003C045",
                @"338D0CEA231458BD00FA5F75",
            ],
            @"defaultConfigurationIsVisible" : @"0",
            @"defaultConfigurationName" : @"Release",
            @"isa" : @"XCConfigurationList",
        },
        @"33CC10FC2044A3C60003C045" : @{
            @"baseConfigurationReference" : @"33E5194F232828860026EE4D",
            @"buildSettings" : @{
                @"ASSETCATALOG_COMPILER_APPICON_NAME" : @"AppIcon",
                @"CLANG_ENABLE_MODULES" : @"YES",
                @"CODE_SIGN_ENTITLEMENTS" : @"Runner/DebugProfile.entitlements",
                @"CODE_SIGN_STYLE" : @"Automatic",
                @"COMBINE_HIDPI_IMAGES" : @"YES",
                @"INFOPLIST_FILE" : @"Runner/Info.plist",
                @"LD_RUNPATH_SEARCH_PATHS" : @[
                    @"$(inherited)",
                    @"@executable_path/../Frameworks",
                ],
                @"PROVISIONING_PROFILE_SPECIFIER" : @"",
                @"SWIFT_OPTIMIZATION_LEVEL" : @"-Onone",
                @"SWIFT_VERSION" : @"5.0",
            },
            @"isa" : @"XCBuildConfiguration",
            @"name" : @"Debug",
        },
        @"33CC10FD2044A3C60003C045" : @{
            @"baseConfigurationReference" : @"33E5194F232828860026EE4D",
            @"buildSettings" : @{
                @"ASSETCATALOG_COMPILER_APPICON_NAME" : @"AppIcon",
                @"CLANG_ENABLE_MODULES" : @"YES",
                @"CODE_SIGN_ENTITLEMENTS" : @"Runner/Release.entitlements",
                @"CODE_SIGN_STYLE" : @"Automatic",
                @"COMBINE_HIDPI_IMAGES" : @"YES",
                @"INFOPLIST_FILE" : @"Runner/Info.plist",
                @"LD_RUNPATH_SEARCH_PATHS" : @[
                    @"$(inherited)",
                    @"@executable_path/../Frameworks",
                ],
                @"PROVISIONING_PROFILE_SPECIFIER" : @"",
                @"SWIFT_VERSION" : @"5.0",
            },
            @"isa" : @"XCBuildConfiguration",
            @"name" : @"Release",
        },
        @"33CC110E2044A8840003C045" : @{
            @"buildActionMask" : @"2147483647",
            @"dstPath" : @"",
            @"dstSubfolderSpec" : @"10",
            @"files" : @[
            ],
            @"isa" : @"PBXCopyFilesBuildPhase",
            @"name" : @"Bundle Framework",
            @"runOnlyForDeploymentPostprocessing" : @"0",
        },
        @"33CC111A2044C6BA0003C045" : @{
            @"buildConfigurationList" : @"33CC111B2044C6BA0003C045",
            @"buildPhases" : @[
                @"33CC111E2044C6BF0003C045",
            ],
            @"dependencies" : @[
            ],
            @"isa" : @"PBXAggregateTarget",
            @"name" : @"Flutter Assemble",
            @"productName" : @"FLX",
        },
        @"33CC111B2044C6BA0003C045" : @{
            @"buildConfigurations" : @[
                @"33CC111C2044C6BA0003C045",
                @"33CC111D2044C6BA0003C045",
                @"338D0CEB231458BD00FA5F75",
            ],
            @"defaultConfigurationIsVisible" : @"0",
            @"defaultConfigurationName" : @"Release",
            @"isa" : @"XCConfigurationList",
        },
        @"33CC111C2044C6BA0003C045" : @{
            @"buildSettings" : @{
                @"CODE_SIGN_STYLE" : @"Manual",
                @"PRODUCT_NAME" : @"$(TARGET_NAME)",
            },
            @"isa" : @"XCBuildConfiguration",
            @"name" : @"Debug",
        },
        @"33CC111D2044C6BA0003C045" : @{
            @"buildSettings" : @{
                @"CODE_SIGN_STYLE" : @"Automatic",
                @"PRODUCT_NAME" : @"$(TARGET_NAME)",
            },
            @"isa" : @"XCBuildConfiguration",
            @"name" : @"Release",
        },
        @"33CC111E2044C6BF0003C045" : @{
            @"buildActionMask" : @"2147483647",
            @"files" : @[
            ],
            @"inputFileListPaths" : @[
                @"Flutter/ephemeral/FlutterInputs.xcfilelist",
            ],
            @"inputPaths" : @[
                @"Flutter/ephemeral/tripwire",
            ],
            @"isa" : @"PBXShellScriptBuildPhase",
            @"outputFileListPaths" : @[
                @"Flutter/ephemeral/FlutterOutputs.xcfilelist",
            ],
            @"outputPaths" : @[
            ],
            @"runOnlyForDeploymentPostprocessing" : @"0",
            @"shellPath" : @"/bin/sh",
            @"shellScript" : @"\"$FLUTTER_ROOT\"/packages/flutter_tools/bin/macos_assemble.sh && touch Flutter/ephemeral/tripwire",
        },
        @"33CC111F2044C79F0003C045" : @{
            @"containerPortal" : @"33CC10E52044A3C60003C045",
            @"isa" : @"PBXContainerItemProxy",
            @"proxyType" : @"1",
            @"remoteGlobalIDString" : @"33CC111A2044C6BA0003C045",
            @"remoteInfo" : @"FLX",
        },
        @"33CC11122044BFA00003C045" : @{
            @"isa" : @"PBXFileReference",
            @"lastKnownFileType" : @"sourcecode.swift",
            @"path" : @"MainFlutterWindow.swift",
            @"sourceTree" : @"<group>",
        },
        @"33CC11132044BFA00003C045" : @{
            @"fileRef" : @"33CC11122044BFA00003C045",
            @"isa" : @"PBXBuildFile",
        },
        @"33CC11202044C79F0003C045" : @{
            @"isa" : @"PBXTargetDependency",
            @"target" : @"33CC111A2044C6BA0003C045",
            @"targetProxy" : @"33CC111F2044C79F0003C045",
        },
        @"33CC11242044D66E0003C045" : @{
            @"children" : @[
                @"33CC10F22044A3C60003C045",
                @"33CC10F42044A3C60003C045",
                @"33CC10F72044A3C60003C045",
            ],
            @"isa" : @"PBXGroup",
            @"name" : @"Resources",
            @"path" : @"..",
            @"sourceTree" : @"<group>",
        },
        @"33CEB47122A05771004F2AC0" : @{
            @"children" : @[
                @"78E0A7A72DC9AD7400C4905E",
                @"335BBD1A22A9A15E00E9071D",
                @"33CEB47222A05771004F2AC0",
                @"33CEB47422A05771004F2AC0",
                @"33CEB47722A0578A004F2AC0",
            ],
            @"isa" : @"PBXGroup",
            @"path" : @"Flutter",
            @"sourceTree" : @"<group>",
        },
        @"33CEB47222A05771004F2AC0" : @{
            @"isa" : @"PBXFileReference",
            @"lastKnownFileType" : @"text.xcconfig",
            @"path" : @"Flutter-Debug.xcconfig",
            @"sourceTree" : @"<group>",
        },
        @"33CEB47422A05771004F2AC0" : @{
            @"isa" : @"PBXFileReference",
            @"lastKnownFileType" : @"text.xcconfig",
            @"path" : @"Flutter-Release.xcconfig",
            @"sourceTree" : @"<group>",
        },
        @"33CEB47722A0578A004F2AC0" : @{
            @"isa" : @"PBXFileReference",
            @"lastKnownFileType" : @"text.xcconfig",
            @"name" : @"Flutter-Generated.xcconfig",
            @"path" : @"ephemeral/Flutter-Generated.xcconfig",
            @"sourceTree" : @"<group>",
        },
        @"33E5194F232828860026EE4D" : @{
            @"isa" : @"PBXFileReference",
            @"lastKnownFileType" : @"text.xcconfig",
            @"path" : @"AppInfo.xcconfig",
            @"sourceTree" : @"<group>",
        },
        @"33E51913231747F40026EE4D" : @{
            @"isa" : @"PBXFileReference",
            @"lastKnownFileType" : @"text.plist.entitlements",
            @"path" : @"DebugProfile.entitlements",
            @"sourceTree" : @"<group>",
        },
        @"33E51914231749380026EE4D" : @{
            @"fileEncoding" : @"4",
            @"isa" : @"PBXFileReference",
            @"lastKnownFileType" : @"text.plist.entitlements",
            @"path" : @"Release.entitlements",
            @"sourceTree" : @"<group>",
        },
        @"33FAB671232836740065AC1E" : @{
            @"children" : @[
                @"33CC10F02044A3C60003C045",
                @"33CC11122044BFA00003C045",
                @"33E51913231747F40026EE4D",
                @"33E51914231749380026EE4D",
                @"33CC11242044D66E0003C045",
                @"33BA886A226E78AF003329D5",
            ],
            @"isa" : @"PBXGroup",
            @"path" : @"Runner",
            @"sourceTree" : @"<group>",
        },
        @"78A3181F2AECB46A00862997" : @{
            @"isa" : @"XCSwiftPackageProductDependency",
            @"productName" : @"FlutterGeneratedPluginSwiftPackage",
        },
        @"78A318202AECB46A00862997" : @{
            @"isa" : @"PBXBuildFile",
            @"productRef" : @"78A3181F2AECB46A00862997",
        },
        @"78E0A7A72DC9AD7400C4905E" : @{
            @"isa" : @"PBXFileReference",
            @"lastKnownFileType" : @"wrapper",
            @"name" : @"FlutterGeneratedPluginSwiftPackage",
            @"path" : @"ephemeral/Packages/FlutterGeneratedPluginSwiftPackage",
            @"sourceTree" : @"<group>",
        },
        @"291CFBF5D6161F772CC18BCF" : @{
            @"isa" : @"PBXFileReference",
            @"lastKnownFileType" : @"text.plist.xml",
            @"name" : @"Info.plist",
            @"path" : @"WorldClockWidget/Info.plist",
            @"sourceTree" : @"SOURCE_ROOT",
        },
        @"331C80D1294CF70F00263BE5" : @{
            @"buildActionMask" : @"2147483647",
            @"files" : @[
                @"331C80D8294CF71000263BE5",
            ],
            @"isa" : @"PBXSourcesBuildPhase",
            @"runOnlyForDeploymentPostprocessing" : @"0",
        },
        @"331C80D2294CF70F00263BE5" : @{
            @"buildActionMask" : @"2147483647",
            @"files" : @[
            ],
            @"isa" : @"PBXFrameworksBuildPhase",
            @"runOnlyForDeploymentPostprocessing" : @"0",
        },
        @"331C80D3294CF70F00263BE5" : @{
            @"buildActionMask" : @"2147483647",
            @"files" : @[
            ],
            @"isa" : @"PBXResourcesBuildPhase",
            @"runOnlyForDeploymentPostprocessing" : @"0",
        },
        @"331C80D4294CF70F00263BE5" : @{
            @"buildConfigurationList" : @"331C80DE294CF71000263BE5",
            @"buildPhases" : @[
                @"331C80D1294CF70F00263BE5",
                @"331C80D2294CF70F00263BE5",
                @"331C80D3294CF70F00263BE5",
            ],
            @"buildRules" : @[
            ],
            @"dependencies" : @[
                @"331C80DA294CF71000263BE5",
            ],
            @"isa" : @"PBXNativeTarget",
            @"name" : @"RunnerTests",
            @"productName" : @"RunnerTests",
            @"productReference" : @"331C80D5294CF71000263BE5",
            @"productType" : @"com.apple.product-type.bundle.unit-test",
        },
        @"331C80D5294CF71000263BE5" : @{
            @"explicitFileType" : @"wrapper.cfbundle",
            @"includeInIndex" : @"0",
            @"isa" : @"PBXFileReference",
            @"path" : @"RunnerTests.xctest",
            @"sourceTree" : @"BUILT_PRODUCTS_DIR",
        },
        @"331C80D6294CF71000263BE5" : @{
            @"children" : @[
                @"331C80D7294CF71000263BE5",
            ],
            @"isa" : @"PBXGroup",
            @"path" : @"RunnerTests",
            @"sourceTree" : @"<group>",
        },
        @"331C80D7294CF71000263BE5" : @{
            @"isa" : @"PBXFileReference",
            @"lastKnownFileType" : @"sourcecode.swift",
            @"path" : @"RunnerTests.swift",
            @"sourceTree" : @"<group>",
        },
        @"331C80D8294CF71000263BE5" : @{
            @"fileRef" : @"331C80D7294CF71000263BE5",
            @"isa" : @"PBXBuildFile",
        },
        @"331C80D9294CF71000263BE5" : @{
            @"containerPortal" : @"33CC10E52044A3C60003C045",
            @"isa" : @"PBXContainerItemProxy",
            @"proxyType" : @"1",
            @"remoteGlobalIDString" : @"33CC10EC2044A3C60003C045",
            @"remoteInfo" : @"Runner",
        },
        @"331C80DA294CF71000263BE5" : @{
            @"isa" : @"PBXTargetDependency",
            @"target" : @"33CC10EC2044A3C60003C045",
            @"targetProxy" : @"331C80D9294CF71000263BE5",
        },
        @"331C80DB294CF71000263BE5" : @{
            @"buildSettings" : @{
                @"BUNDLE_LOADER" : @"$(TEST_HOST)",
                @"CURRENT_PROJECT_VERSION" : @"1",
                @"GENERATE_INFOPLIST_FILE" : @"YES",
                @"MARKETING_VERSION" : @"1.0",
                @"PRODUCT_BUNDLE_IDENTIFIER" : @"com.example.worldClock.RunnerTests",
                @"PRODUCT_NAME" : @"$(TARGET_NAME)",
                @"SWIFT_VERSION" : @"5.0",
                @"TEST_HOST" : @"$(BUILT_PRODUCTS_DIR)/world_clock.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/world_clock",
            },
            @"isa" : @"XCBuildConfiguration",
            @"name" : @"Debug",
        },
        @"331C80DC294CF71000263BE5" : @{
            @"buildSettings" : @{
                @"BUNDLE_LOADER" : @"$(TEST_HOST)",
                @"CURRENT_PROJECT_VERSION" : @"1",
                @"GENERATE_INFOPLIST_FILE" : @"YES",
                @"MARKETING_VERSION" : @"1.0",
                @"PRODUCT_BUNDLE_IDENTIFIER" : @"com.example.worldClock.RunnerTests",
                @"PRODUCT_NAME" : @"$(TARGET_NAME)",
                @"SWIFT_VERSION" : @"5.0",
                @"TEST_HOST" : @"$(BUILT_PRODUCTS_DIR)/world_clock.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/world_clock",
            },
            @"isa" : @"XCBuildConfiguration",
            @"name" : @"Release",
        },
        @"331C80DD294CF71000263BE5" : @{
            @"buildSettings" : @{
                @"BUNDLE_LOADER" : @"$(TEST_HOST)",
                @"CURRENT_PROJECT_VERSION" : @"1",
                @"GENERATE_INFOPLIST_FILE" : @"YES",
                @"MARKETING_VERSION" : @"1.0",
                @"PRODUCT_BUNDLE_IDENTIFIER" : @"com.example.worldClock.RunnerTests",
                @"PRODUCT_NAME" : @"$(TARGET_NAME)",
                @"SWIFT_VERSION" : @"5.0",
                @"TEST_HOST" : @"$(BUILT_PRODUCTS_DIR)/world_clock.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/world_clock",
            },
            @"isa" : @"XCBuildConfiguration",
            @"name" : @"Profile",
        },
        @"331C80DE294CF71000263BE5" : @{
            @"buildConfigurations" : @[
                @"331C80DB294CF71000263BE5",
                @"331C80DC294CF71000263BE5",
                @"331C80DD294CF71000263BE5",
            ],
            @"defaultConfigurationIsVisible" : @"0",
            @"defaultConfigurationName" : @"Release",
            @"isa" : @"XCConfigurationList",
        },
        @"335BBD1A22A9A15E00E9071D" : @{
            @"fileEncoding" : @"4",
            @"isa" : @"PBXFileReference",
            @"lastKnownFileType" : @"sourcecode.swift",
            @"path" : @"GeneratedPluginRegistrant.swift",
            @"sourceTree" : @"<group>",
        },
        @"335BBD1B22A9A15E00E9071D" : @{
            @"fileRef" : @"335BBD1A22A9A15E00E9071D",
            @"isa" : @"PBXBuildFile",
        },
        @"338D0CE9231458BD00FA5F75" : @{
            @"baseConfigurationReference" : @"7AFA3C8E1D35360C0083082E",
            @"buildSettings" : @{
                @"ALWAYS_SEARCH_USER_PATHS" : @"NO",
                @"ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS" : @"YES",
                @"CLANG_ANALYZER_NONNULL" : @"YES",
                @"CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION" : @"YES_AGGRESSIVE",
                @"CLANG_CXX_LANGUAGE_STANDARD" : @"gnu++14",
                @"CLANG_CXX_LIBRARY" : @"libc++",
                @"CLANG_ENABLE_MODULES" : @"YES",
                @"CLANG_ENABLE_OBJC_ARC" : @"YES",
                @"CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING" : @"YES",
                @"CLANG_WARN_BOOL_CONVERSION" : @"YES",
                @"CLANG_WARN_CONSTANT_CONVERSION" : @"YES",
                @"CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS" : @"YES",
                @"CLANG_WARN_DIRECT_OBJC_ISA_USAGE" : @"YES_ERROR",
                @"CLANG_WARN_DOCUMENTATION_COMMENTS" : @"YES",
                @"CLANG_WARN_EMPTY_BODY" : @"YES",
                @"CLANG_WARN_ENUM_CONVERSION" : @"YES",
                @"CLANG_WARN_INFINITE_RECURSION" : @"YES",
                @"CLANG_WARN_INT_CONVERSION" : @"YES",
                @"CLANG_WARN_NON_LITERAL_NULL_CONVERSION" : @"YES",
                @"CLANG_WARN_OBJC_LITERAL_CONVERSION" : @"YES",
                @"CLANG_WARN_OBJC_ROOT_CLASS" : @"YES_ERROR",
                @"CLANG_WARN_RANGE_LOOP_ANALYSIS" : @"YES",
                @"CLANG_WARN_SUSPICIOUS_MOVE" : @"YES",
                @"CODE_SIGN_IDENTITY" : @"-",
                @"COPY_PHASE_STRIP" : @"NO",
                @"DEAD_CODE_STRIPPING" : @"YES",
                @"DEBUG_INFORMATION_FORMAT" : @"dwarf-with-dsym",
                @"ENABLE_NS_ASSERTIONS" : @"NO",
                @"ENABLE_STRICT_OBJC_MSGSEND" : @"YES",
                @"ENABLE_USER_SCRIPT_SANDBOXING" : @"NO",
                @"GCC_C_LANGUAGE_STANDARD" : @"gnu11",
                @"GCC_NO_COMMON_BLOCKS" : @"YES",
                @"GCC_WARN_64_TO_32_BIT_CONVERSION" : @"YES",
                @"GCC_WARN_ABOUT_RETURN_TYPE" : @"YES_ERROR",
                @"GCC_WARN_UNINITIALIZED_AUTOS" : @"YES_AGGRESSIVE",
                @"GCC_WARN_UNUSED_FUNCTION" : @"YES",
                @"GCC_WARN_UNUSED_VARIABLE" : @"YES",
                @"MACOSX_DEPLOYMENT_TARGET" : @"10.15",
                @"MTL_ENABLE_DEBUG_INFO" : @"NO",
                @"SDKROOT" : @"macosx",
                @"SWIFT_COMPILATION_MODE" : @"wholemodule",
                @"SWIFT_OPTIMIZATION_LEVEL" : @"-O",
            },
            @"isa" : @"XCBuildConfiguration",
            @"name" : @"Profile",
        },
        @"338D0CEA231458BD00FA5F75" : @{
            @"baseConfigurationReference" : @"33E5194F232828860026EE4D",
            @"buildSettings" : @{
                @"ASSETCATALOG_COMPILER_APPICON_NAME" : @"AppIcon",
                @"CLANG_ENABLE_MODULES" : @"YES",
                @"CODE_SIGN_ENTITLEMENTS" : @"Runner/DebugProfile.entitlements",
                @"CODE_SIGN_STYLE" : @"Automatic",
                @"COMBINE_HIDPI_IMAGES" : @"YES",
                @"INFOPLIST_FILE" : @"Runner/Info.plist",
                @"LD_RUNPATH_SEARCH_PATHS" : @[
                    @"$(inherited)",
                    @"@executable_path/../Frameworks",
                ],
                @"PROVISIONING_PROFILE_SPECIFIER" : @"",
                @"SWIFT_VERSION" : @"5.0",
            },
            @"isa" : @"XCBuildConfiguration",
            @"name" : @"Profile",
        },
        @"338D0CEB231458BD00FA5F75" : @{
            @"buildSettings" : @{
                @"CODE_SIGN_STYLE" : @"Manual",
                @"PRODUCT_NAME" : @"$(TARGET_NAME)",
            },
            @"isa" : @"XCBuildConfiguration",
            @"name" : @"Profile",
        },
        @"372F46F5027C2809D7406829" : @{
            @"buildActionMask" : @2147483647,
            @"dstPath" : @"",
            @"dstSubfolderSpec" : @13,
            @"files" : @[
                @"1B5F23F33664958D5B778682",
            ],
            @"isa" : @"PBXCopyFilesBuildPhase",
            @"name" : @"Embed Foundation Extensions",
            @"runOnlyForDeploymentPostprocessing" : @0,
        },
        @"419DB430E6155665316D6F72" : @{
            @"fileRef" : @"581C54E99A2F2EE6F76DFF75",
            @"isa" : @"PBXBuildFile",
        },
        @"581C54E99A2F2EE6F76DFF75" : @{
            @"isa" : @"PBXFileReference",
            @"lastKnownFileType" : @"text.json",
            @"name" : @"world_dots.json",
            @"path" : @"WorldClockWidget/world_dots.json",
            @"sourceTree" : @"SOURCE_ROOT",
        },
        @"781AD8BC2B33823900A9FFBB" : @{
            @"isa" : @"XCLocalSwiftPackageReference",
            @"relativePath" : @"Flutter/ephemeral/Packages/FlutterGeneratedPluginSwiftPackage",
        },
        @"924A62FDA3B40BC9FE5B372E" : @{
            @"children" : @[
                @"C9DD1430B4AE093DFFE8E01C",
                @"4FCD6F3A563B65A71839C33E",
                @"954DCB8468B76863501BCD5E",
                @"581C54E99A2F2EE6F76DFF75",
                @"291CFBF5D6161F772CC18BCF",
            ],
            @"isa" : @"PBXGroup",
            @"name" : @"WorldClockWidget",
            @"sourceTree" : @"<group>",
        },
        @"954DCB8468B76863501BCD5E" : @{
            @"isa" : @"PBXFileReference",
            @"lastKnownFileType" : @"sourcecode.swift",
            @"name" : @"WorldDotMapRenderer.swift",
            @"path" : @"WorldClockWidget/WorldDotMapRenderer.swift",
            @"sourceTree" : @"SOURCE_ROOT",
        },
        @"3399D490228B24CF009A79C7" : @{
            @"alwaysOutOfDate" : @"1",
            @"buildActionMask" : @"2147483647",
            @"files" : @[
            ],
            @"inputFileListPaths" : @[
            ],
            @"inputPaths" : @[
            ],
            @"isa" : @"PBXShellScriptBuildPhase",
            @"outputFileListPaths" : @[
            ],
            @"outputPaths" : @[
            ],
            @"runOnlyForDeploymentPostprocessing" : @"0",
            @"shellPath" : @"/bin/sh",
            @"shellScript" : @"echo \"$PRODUCT_NAME.app\" > \"$PROJECT_DIR\"/Flutter/ephemeral/.app_filename && \"$FLUTTER_ROOT\"/packages/flutter_tools/bin/macos_assemble.sh embed
",
        },
        @"9740EEB21CF90195004384FC" : @{
            @"fileEncoding" : @"4",
            @"isa" : @"PBXFileReference",
            @"lastKnownFileType" : @"text.xcconfig",
            @"path" : @"Debug.xcconfig",
            @"sourceTree" : @"<group>",
        },
        @"333000ED22D3DE5D00554162" : @{
            @"isa" : @"PBXFileReference",
            @"lastKnownFileType" : @"text.xcconfig",
            @"path" : @"Warnings.xcconfig",
            @"sourceTree" : @"<group>",
        },
        @"413131E9E0B122613137EFB8" : @{
            @"fileRef" : @"4FCD6F3A563B65A71839C33E",
            @"isa" : @"PBXBuildFile",
        },
        @"A28F36DB2E18C8C4A691B925" : @{
            @"buildConfigurationList" : @"CD1643728ED11418197F347C",
            @"buildPhases" : @[
                @"1AE116F6C05CAC852900401C",
                @"C24E077B5778E803F9174C51",
                @"A2675A6490E4A643E1DA4CC7",
            ],
            @"buildRules" : @[
            ],
            @"dependencies" : @[
            ],
            @"isa" : @"PBXNativeTarget",
            @"name" : @"WorldClockWidget",
            @"productName" : @"WorldClockWidget",
            @"productReference" : @"8A2CA69581E78374CE81A0A7",
            @"productType" : @"com.apple.product-type.app-extension",
        },
        @"A93D3CE89E7AAA28EA82DA7A" : @{
            @"buildSettings" : @{
                @"CODE_SIGN_IDENTITY" : @"-",
                @"CODE_SIGN_STYLE" : @"Automatic",
                @"COMBINE_HIDPI_IMAGES" : @"YES",
                @"CURRENT_PROJECT_VERSION" : @"1",
                @"ENABLE_HARDENED_RUNTIME" : @"YES",
                @"GENERATE_INFOPLIST_FILE" : @"NO",
                @"INFOPLIST_FILE" : @"WorldClockWidget/Info.plist",
                @"LD_RUNPATH_SEARCH_PATHS" : @[
                    @"$(inherited)",
                    @"@executable_path/../Frameworks",
                    @"@executable_path/../../../../Frameworks",
                ],
                @"MACOSX_DEPLOYMENT_TARGET" : @"14.0",
                @"MARKETING_VERSION" : @"1.0",
                @"PRODUCT_BUNDLE_IDENTIFIER" : @"com.example.worldClock.WorldClockWidget",
                @"PRODUCT_NAME" : @"$(TARGET_NAME)",
                @"SKIP_INSTALL" : @"YES",
                @"SWIFT_ACTIVE_COMPILATION_CONDITIONS" : @"DEBUG",
                @"SWIFT_OPTIMIZATION_LEVEL" : @"-Onone",
                @"SWIFT_VERSION" : @"5.0",
            },
            @"isa" : @"XCBuildConfiguration",
            @"name" : @"Debug",
        },
        @"A697FA7F34CF00352EEC4B8B" : @{
            @"fileRef" : @"954DCB8468B76863501BCD5E",
            @"isa" : @"PBXBuildFile",
        },
        @"A2675A6490E4A643E1DA4CC7" : @{
            @"buildActionMask" : @2147483647,
            @"files" : @[
                @"419DB430E6155665316D6F72",
            ],
            @"isa" : @"PBXResourcesBuildPhase",
            @"runOnlyForDeploymentPostprocessing" : @0,
        },
        @"AF982C065F28985B78EC108A" : @{
            @"fileRef" : @"C9DD1430B4AE093DFFE8E01C",
            @"isa" : @"PBXBuildFile",
        },
        @"C9DD1430B4AE093DFFE8E01C" : @{
            @"isa" : @"PBXFileReference",
            @"lastKnownFileType" : @"sourcecode.swift",
            @"name" : @"WorldClockWidget.swift",
            @"path" : @"WorldClockWidget/WorldClockWidget.swift",
            @"sourceTree" : @"SOURCE_ROOT",
        },
        @"C24E077B5778E803F9174C51" : @{
            @"buildActionMask" : @2147483647,
            @"files" : @[
            ],
            @"isa" : @"PBXFrameworksBuildPhase",
            @"runOnlyForDeploymentPostprocessing" : @0,
        },
        @"C484BFB6AEA6ACBCE67A027E" : @{
            @"buildSettings" : @{
                @"CODE_SIGN_IDENTITY" : @"-",
                @"CODE_SIGN_STYLE" : @"Automatic",
                @"COMBINE_HIDPI_IMAGES" : @"YES",
                @"CURRENT_PROJECT_VERSION" : @"1",
                @"ENABLE_HARDENED_RUNTIME" : @"YES",
                @"GENERATE_INFOPLIST_FILE" : @"NO",
                @"INFOPLIST_FILE" : @"WorldClockWidget/Info.plist",
                @"LD_RUNPATH_SEARCH_PATHS" : @[
                    @"$(inherited)",
                    @"@executable_path/../Frameworks",
                    @"@executable_path/../../../../Frameworks",
                ],
                @"MACOSX_DEPLOYMENT_TARGET" : @"14.0",
                @"MARKETING_VERSION" : @"1.0",
                @"PRODUCT_BUNDLE_IDENTIFIER" : @"com.example.worldClock.WorldClockWidget",
                @"PRODUCT_NAME" : @"$(TARGET_NAME)",
                @"SKIP_INSTALL" : @"YES",
                @"SWIFT_VERSION" : @"5.0",
            },
            @"isa" : @"XCBuildConfiguration",
            @"name" : @"Release",
        },
        @"CD1643728ED11418197F347C" : @{
            @"buildConfigurations" : @[
                @"A93D3CE89E7AAA28EA82DA7A",
                @"C484BFB6AEA6ACBCE67A027E",
            ],
            @"defaultConfigurationIsVisible" : @0,
            @"defaultConfigurationName" : @"Release",
            @"isa" : @"XCConfigurationList",
        },
        @"D73912EC22F37F3D000D13A0" : @{
            @"children" : @[
            ],
            @"isa" : @"PBXGroup",
            @"name" : @"Frameworks",
            @"sourceTree" : @"<group>",
        },
    },
    @"objectVersion" : @"54",
    @"rootObject" : @"33CC10E52044A3C60003C045",
};
